/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GetATutorRouteImport } from './routes/get-a-tutor'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeTestIdRouteImport } from './routes/practice.$testId'

const GetATutorRoute = GetATutorRouteImport.update({
  id: '/get-a-tutor',
  path: '/get-a-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeTestIdRoute = PracticeTestIdRouteImport.update({
  id: '/practice/$testId',
  path: '/practice/$testId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-a-tutor': typeof GetATutorRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-a-tutor': typeof GetATutorRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/practice': typeof PracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-a-tutor': typeof GetATutorRoute
  '/practice/$testId': typeof PracticeTestIdRoute
  '/practice/': typeof PracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/get-a-tutor'
    | '/practice/$testId'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/get-a-tutor' | '/practice/$testId' | '/practice'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/get-a-tutor'
    | '/practice/$testId'
    | '/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GetATutorRoute: typeof GetATutorRoute
  PracticeTestIdRoute: typeof PracticeTestIdRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/get-a-tutor': {
      id: '/get-a-tutor'
      path: '/get-a-tutor'
      fullPath: '/get-a-tutor'
      preLoaderRoute: typeof GetATutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$testId': {
      id: '/practice/$testId'
      path: '/practice/$testId'
      fullPath: '/practice/$testId'
      preLoaderRoute: typeof PracticeTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GetATutorRoute: GetATutorRoute,
  PracticeTestIdRoute: PracticeTestIdRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
